# Generated by Django 4.0.1 on 2022-01-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellopeople', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='id',
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, verbose_name="Ім'я"),
        ),
    ]
