# Generated by Django 4.0.1 on 2022-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellopeople', '0002_remove_name_id_alter_name_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=65, primary_key=True, serialize=False, verbose_name="Ім'я"),
        ),
    ]
