# Generated by Django 4.0.1 on 2022-01-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellopeople', '0003_alter_name_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='surname',
        ),
    ]
